### ISSUE TITLE
Building for 1.9.4?

### ISSUE THREAD

**Issue by RevoSucks** [Mrbrutal/Traincraft-5#17]
This is technically not an issue, but since the description of this repo says `for 1.7.x and 1.8.x version of Minecraft and beyond` is it possible to build this source for 1.8.x? I try to setup a new MDK using 1.8.9 or so, do the usual gradlew eclipse setup, delete example mod, make the property changes then I get this:

```
* What went wrong:
A problem occurred configuring root project 'tcsource18'.
> Could not resolve all dependencies for configuration ':deobfCompile'.
   > Could not resolve mezz.jei:jei_1.8:3.3.3.197.
     Required by:
         si.meansoft.traincraft:tcsource18:1.0.0
      > Could not resolve mezz.jei:jei_1.8:3.3.3.197.
         > Could not get resource 'https://libraries.minecraft.net/mezz/jei/jei_1.8/3.3.3.197/jei_1.8-3.3.3.197.pom'.
            > Could not GET 'https://libraries.minecraft.net/mezz/jei/jei_1.8/3.3.3.197/jei_1.8-3.3.3.197.pom'. Received status code 403 from server: Forbidden
```

Regardless of the properties config, i get an error similar to this. (I tried both 1.8 and 1.8.9 just in case)

Is building for 1.8.x and 1.7.x is just a gesture or is there something im not doing?

I can build for 1.9 just fine, by the way.

**Comment by EternalBlueFlame** [comment]
This is meant for 1.9, not 1.8 or 1.7.
We never did, and never will intend to support 1.8, at this stage of development for forge and all the other mods it would be a waste of time to support 1.8.
1.7 however does have it's own branch back at [https://github.com/EternalBlueFlame/Traincraft-5](https://github.com/EternalBlueFlame/Traincraft-5)

I think axell from buildcraft has a 1.8 branch of TC floating around somewhere, generally abandoned.

The label only says 1.7 and 1.8 because it never got updated after we changed directions back in march-ish.

**Comment by RevoSucks** [comment]
Ok, guess I might as well change this issue to a more productive one. What about support for 1.9.4 since thats what other mods are starting to support? This only builds to 1.9 at the moment.

**Comment by EternalBlueFlame** [comment]
and 1.9 isn't forwards compatible with 1.9.4/1.10?

**Comment by canitzp** [comment]
If you want it then you now have to clone the git repo, open a terminal and type 'gradlew setupDecompWorkspace [idea or eclipse]'

**Comment by RevoSucks** [comment]
I forgot this issue was still even open. Closing.
