### ISSUE TITLE
Passenger Cart do not cooperate with railcraft track

### ISSUE THREAD

**Issue by l89669** [Mrbrutal/Traincraft-5#57]
issue: 
when I place a passenger cart(N.Y. Subway) on Railcraft Hi-Speed Booster track and move it, it's speed boost. But when I place it on a Railcraft Hi-Speed Transition Track, it doesn't speed up or down.
Both tested on redstone activated track and not activated track.

**Comment by EternalBlueFlame** [comment]
Well first off, since this occurs a lot, let me point out this is the repo for the 1.11 rewrite.
If you are here for that, then ignore this reply (I know canitzp has been making good progress so I'm not exactly sure where the 1.11 version stands right now, if these are even bugs able to happen yet or not).


So assuming you are referring to 1.7.10, the issue tracker for that is over here:
[https://github.com/EternalBlueFlame/Traincraft-5/issues](https://github.com/EternalBlueFlame/Traincraft-5/issues)

That also being said, Railcraft overrides a lot of minecart behavior indirectly, in some rare cases TC does not inherit those modifications. Usually either from an incompatible version of Railcraft, or an issue with java, for example the version, or the arguments used to launch the game.
I tested it just now and I can confirm that it is working properly for me with railcraft version 9.12.2.0 and java 8 revision 71.

After all that, if you are still experiencing the issue, and it is for 1.7.10, please open an issue over on the correct tracker, with some more info, and we'll do what we can to help, or maybe even uncover a glitch we didn't know about.

**Comment by l89669** [comment]
Thanks for your answer, I've made an new issue on the right Project.

> https://github.com/EternalBlueFlame/Traincraft-5/issues/254
